MvcGame/Models/Game.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcGame.Models;

public class Game
{
    public int Id { get; set; }
    [StringLength(60, MinimumLength = 3)]
    public string Tytul { get; set; }
    [Display(Name = "Data wydania"), DataType(DataType.Date)]
    public DateTime Data_wydania { get; set; }
    [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$"), Required, StringLength(30)]
    public string Gatunek { get; set; }
    [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$"), StringLength(60)]
    public string Wydawca { get; set; }
    [Range(1, 100), DataType(DataType.Currency)]
    [Column(TypeName = "decimal(18, 2)")]
    public decimal Cena { get; set; }

}

MvcGame/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcGame.Data;
using MvcGame.Models;

namespace MvcGame.Controllers
{
    public class GamesController : Controller
    {
        private readonly MvcGameContext _context;

        public GamesController(MvcGameContext context)
        {
            _context = context;
        }

        // GET: Games
        // GET: Games
        public async Task<IActionResult> Index(string movieGenre, string searchString)
        {
            if (_context.Game == null)
            {
                return Problem("Entity set 'MvcGameContext.Game'  is null.");
            }

            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Game
                                            orderby m.Gatunek
                                            select m.Gatunek;
            var movies = from m in _context.Game
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Tytul!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Gatunek == movieGenre);
            }

            var movieGenreVM = new GameGenreViewModel
            {
                Genres = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Games = await movies.ToListAsync()
            };

            return View(movieGenreVM);
        }

        // GET: Games/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Game == null)
            {
                return NotFound();
            }

            var movie = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Games/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Tytul,Data_wydania,Gatunek,Cena,Wydawca")] Game movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Games/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Game == null)
            {
                return NotFound();
            }

            var movie = await _context.Game.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Tytul,Data_wydania,Gatunek,Cena,Wydawca")] Game movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GameExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Games/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Game == null)
            {
                return NotFound();
            }

            var movie = await _context.Game
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Game == null)
            {
                return Problem("Entity set 'MvcGameContext.Game'  is null.");
            }
            var movie = await _context.Game.FindAsync(id);
            if (movie != null)
            {
                _context.Game.Remove(movie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GameExists(int id)
        {
          return (_context.Game?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MvcGame/Views/Games/Create.cshtml
@model MvcGame.Models.Game

@{
    ViewData["Tytul"] = "Create";
}

<h1>Dodaj</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Tytul" class="control-label"></label>
                <input asp-for="Tytul" class="form-control" />
                <span asp-validation-for="Tytul" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data_wydania" class="control-label"></label>
                <input asp-for="Data_wydania" class="form-control" />
                <span asp-validation-for="Data_wydania" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gatunek" class="control-label"></label>
                <input asp-for="Gatunek" class="form-control" />
                <span asp-validation-for="Gatunek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cena" class="control-label"></label>
                <input asp-for="Cena" class="form-control" />
                <span asp-validation-for="Cena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wydawca" class="control-label"></label>
                <input asp-for="Wydawca" class="form-control" />
                <span asp-validation-for="Wydawca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcGame/Views/Games/Delete.cshtml
@model MvcGame.Models.Game

@{
    ViewData["Tytul"] = "Delete";
}

<h1>Usuwanie</h1>

<h3>Jesteś pewien że chcesz usunąć?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tytul)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tytul)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data_wydania)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_wydania)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gatunek)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gatunek)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wydawca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wydawca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cena)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Wróć do listy</a>
    </form>
</div>

MvcGame/Views/Games/Details.cshtml
@model MvcGame.Models.Game

@{
    ViewData["Tytul"] = "Details";
}

<h1>Szczegóły</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tytul)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tytul)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data_wydania)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data_wydania)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gatunek)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gatunek)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Wydawca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Wydawca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cena)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cena)
        </dd>
        
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edytuj</a> |
    <a asp-action="Index">Wróć do listy</a>
</div>

MvcGame/Views/Games/Edit.cshtml
@model MvcGame.Models.Game

@{
    ViewData["Tytul"] = "Edytuj";
}

<h1>Edytuj</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Tytul" class="control-label"></label>
                <input asp-for="Tytul" class="form-control" />
                <span asp-validation-for="Tytul" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data_wydania" class="control-label"></label>
                <input asp-for="Data_wydania" class="form-control" />
                <span asp-validation-for="Data_wydania" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gatunek" class="control-label"></label>
                <input asp-for="Gatunek" class="form-control" />
                <span asp-validation-for="Gatunek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cena" class="control-label"></label>
                <input asp-for="Cena" class="form-control" />
                <span asp-validation-for="Cena" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Wydawca" class="control-label"></label>
                <input asp-for="Wydawca" class="form-control" />
                <span asp-validation-for="Wydawca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Wróć do listy</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcGame/Views/Games/Index.cshtml
@model MvcGame.Models.GameGenreViewModel

@{
    ViewData["Tytul"] = "Index";
}

<h1>Lista fajnych gierek</h1>

<p>
    <a asp-action="Create">Dodaj nowe</a>
</p>
<form asp-controller="Games" asp-action="Index" method="get">
    <p>

        <select asp-for="GameGenre" asp-items="Model.Genres">
            <option value="">Wszystkie</option>
        </select>

        Tytul: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filtruj" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Games![0].Tytul)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Games![0].Data_wydania)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Games![0].Gatunek)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Games[0].Wydawca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Games![0].Cena)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Games!)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Tytul)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data_wydania)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gatunek)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Wydawca)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cena)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edytuj</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Szczegóły</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Usuń</a>
                </td>
            </tr>
        }
    </tbody>
</table>